spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DATABASE_URL_DEV}
    username: ${DEV_USERNAME}
    password: ${DEV_PASSWORD}
    jpa:
      hibernate:
        ddl-auto: update # Gunakan 'update' agar data tidak hilang saat restart, atau 'create-drop' untuk reset tiap restart
      show-sql: true # Opsional: Untuk melihat query pembuatan tabel di log
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

external:
  api:
    base-url: ${EXTERNAL_API_BASE_URL}

api:
  key: ${API_KEY}
