server:
  port: 8082
spring:
  application:
    name: vehicle-rental-be
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  profiles:
    active: 'dev'
  jpa:
    hibernate:
      ddl-auto: create-drop

external:
  api:
    base-url: https://acc-be.beel.my.id/api

api:
  key: your-secret-api-key-here