spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DATABASE_URL_DEV}
    username: ${DEV_USERNAME}
    password: ${DEV_PASSWORD}

external:
  api:
    base-url: ${EXTERNAL_API_BASE_URL}

api:
  key: ${API_KEY}